---
title: "League of Legends Match Info"
author: "Michael Chiang"
date: "2/5/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/michael/prediction-lol")
```

```{r}
#Keep track of packages we install
#install.packages("magrittr")
#install.packages("dplyr")
```



```{r}
#read in data set
matchinfo  <- read.csv(file = "matchinfo.csv")
```


```{r}
matchinfoNew <- subset(matchinfo, 
                       select = c('bResult','rResult','blueADCChamp','blueSupportChamp','redADCChamp','redSupportChamp'))
```

Begin process of cleaning data, so only marksman are in it.

```{r}
# Take out non "Marksman" champions
# List taken from http://leagueoflegends.wikia.com/wiki/ADC
marksmanList <- c("Ashe","Caitlyn","Corki","Draven","Ezreal","Graves","Jhin","Jinx","Kalista","Kindred","Kogmaw","Lucian","Miss Fortune","Quinn","Sivir","Tristana","Twitch","Varus","Vayne","Vayne","Xayah")

CleanedmatchinfoNew <- subset(matchinfoNew, blueADCChamp %in% marksmanList)
CleanedmatchinfoNew <- subset(CleanedmatchinfoNew,redADCChamp %in% marksmanList)
```
There are 6799 observations left cleaned out from 7620 observations
Clean out support champions

```{r}
# Take out non "Support" champions
# List taken from http://leagueoflegends.wikia.com/wiki/Category:Support_champion
supportList <- c("Alistar","Annie","Bard","Blitzcrank","Brand","Braum","Fiddlesticks","Galio","Janna","Karma"
                  ,"Kennen","Leona","Lulu","Lux","Malphite","Miss Fortune","Morgana","Nami","Nautilus","Ornn",
                  "Poppy","Rakan","Shen","Sion","Sona","Soraka","Tahm Kench","Taric","Teemo","Thresh","Trundle",
                  "Veigar","Velkoz","Xerath","Zilean","Zoe","Zyra")

CleanedmatchinfoNew <- subset(CleanedmatchinfoNew, blueSupportChamp %in% supportList)
CleanedmatchinfoNew <- subset(CleanedmatchinfoNew, redSupportChamp %in% supportList)
```
There are 5701 observations left cleaned out from 6799 observations.

Create Ashe/Alistar Dataset
```{r}
asheAliB <- subset(CleanedmatchinfoNew, blueADCChamp == "Ashe" & blueSupportChamp == "Alistar")
asheAliR <- subset(CleanedmatchinfoNew, redADCChamp == "Ashe" & redSupportChamp == "Alistar")

asheAli <- rbind(asheAliB, asheAliR)
```

85 total observations of Ashe and Alistar combinations.
```{r}
# Total number of Ashe Alistar wins on blue side
sum(asheAliB$bResult == 1)

# Total number of Ashe Alistar wins on red side
sum(asheAliR$rResult == 1)

asheAliWinTotal <- sum(asheAliB$bResult == 1) + sum(asheAliR$rResult == 1)
asheAliWinRate <- asheAliWinTotal/85
asheAliWinTotal
asheAliWinRate
```

